name: Build and push

on:
  push:
    branches:
      - devel

jobs:
  build:
    name: Build and push job
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"
          cache: maven

      - uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.9.0

      - name: Give permissions
        run: |
          sudo chmod 777 ../
        shell: bash

      - name: Set up NodeJs 20
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: yarn
          cache-dependency-path: webapp/yarn.lock

      - name: Run build script
        run: ./build.sh
        shell: bash
        working-directory: ./deploy

      - name: Build Docker Image
        env:
          REGISTRY: registry.cn-chengdu.aliyuncs.com
        shell: bash
        working-directory: ./deploy
        run: |
          echo "${{ secrets.ALIYUN_PASSWORD }}" | docker login $REGISTRY -u "${{ secrets.ALIYUN_USERNAME }}" --password-stdin
          bash ./build_and_push.sh